'use client'

import { useMemo, useState } from 'react'
import {
  Activity, AlertTriangle, ArrowUpRight, Bell, Boxes, Check, ChevronDown,
  ClipboardCheck, Clock3, CloudRain, FileText, Gauge, HeartHandshake,
  LayoutDashboard, ListFilter, LockKeyhole, MapPin, Menu, Moon, Package,
  Radio, Search, Settings, ShieldCheck, Sun, Truck, Users, X, Zap,
} from 'lucide-react'

type Section = 'Dashboard' | 'Incidents' | 'Relief Requests' | 'Inventory' | 'Shelters' | 'Volunteers' | 'Deliveries' | 'Audit Trail' | 'Reports & Analytics' | 'Users & Permissions' | 'Decision Support'

const nav = [
  { label: 'Dashboard', icon: LayoutDashboard }, { label: 'Incidents', icon: Radio },
  { label: 'Relief Requests', icon: ClipboardCheck }, { label: 'Inventory', icon: Boxes },
  { label: 'Shelters', icon: HeartHandshake }, { label: 'Volunteers', icon: Users },
  { label: 'Deliveries', icon: Truck }, { label: 'Audit Trail', icon: LockKeyhole },
  { label: 'Reports & Analytics', icon: FileText }, { label: 'Users & Permissions', icon: ShieldCheck },
  { label: 'Decision Support', icon: Zap },
]

const incidents = [
  { id: 'INC-2026-001', type: 'Flood', location: 'Hyderabad', severity: 'Critical', time: '08:32 AM', people: '4,820', status: 'Active', team: 'Delta Response' },
  { id: 'INC-2026-002', type: 'Cyclone', location: 'Coastal Region', severity: 'High', time: '07:45 AM', people: '3,210', status: 'Active', team: 'Coastal Unit' },
  { id: 'INC-2026-003', type: 'Landslide', location: 'Hill Region', severity: 'High', time: '06:20 AM', people: '1,840', status: 'Monitoring', team: 'North Field Ops' },
]
const requests = [
  { id: 'REQ-1024', location: 'Hyderabad', need: 'Water', qty: '1,200 L', severity: 'Critical', affected: '850', urgency: 'Immediate', score: 96, status: 'Pending Approval' },
  { id: 'REQ-1025', location: 'Warangal', need: 'Food Kits', qty: '400', severity: 'High', affected: '420', urgency: 'High', score: 88, status: 'Approved' },
  { id: 'REQ-1026', location: 'Nalgonda', need: 'Medicines', qty: '150', severity: 'High', affected: '300', urgency: 'High', score: 84, status: 'Pending' },
]
const inventory = [
  { id: 'RES-001', name: 'Drinking Water', cat: 'Water', warehouse: 'Central WH', batch: 'B-1209', available: '8,420 L', allocated: '2,100 L', expiry: '—', stock: 82, status: 'Healthy' },
  { id: 'RES-014', name: 'Family Food Kit', cat: 'Food', warehouse: 'Central WH', batch: 'B-1182', available: '3,240 kits', allocated: '1,120', expiry: '18 Nov 26', stock: 64, status: 'Healthy' },
  { id: 'RES-031', name: 'Essential Medicines', cat: 'Medicines', warehouse: 'Medical Hub', batch: 'B-0891', available: '860 packs', allocated: '490', expiry: '12 Oct 26', stock: 28, status: 'Low Stock' },
]
const deliveries = [
  { id: 'DEL-5012', request: 'REQ-1024', resource: 'Drinking Water', qty: '1,200 L', origin: 'Central WH', destination: 'Hyderabad', driver: 'Delta Team 04', time: '09:10 AM', eta: '10:25 AM', status: 'In Transit' },
  { id: 'DEL-5008', request: 'REQ-1017', resource: 'Family Food Kits', qty: '240 kits', origin: 'Central WH', destination: 'Secunderabad', driver: 'Logistics 02', time: '07:40 AM', eta: '08:30 AM', status: 'Confirmed' },
  { id: 'DEL-5004', request: 'REQ-1012', resource: 'Blankets', qty: '180', origin: 'North Hub', destination: 'Nalgonda', driver: 'North Field Ops', time: '06:55 AM', eta: '09:15 AM', status: 'Dispatched' },
]

function StatusBadge({ children, tone = 'neutral' }: { children: React.ReactNode; tone?: string }) {
  return <span className={`badge badge-${tone}`}>{children}</span>
}
function severityTone(value: string) { return value === 'Critical' ? 'critical' : value === 'High' ? 'high' : value === 'Approved' || value === 'Confirmed' ? 'success' : 'warning' }
function KPI({ icon: Icon, label, value, trend, tone }: { icon: React.ElementType; label: string; value: string; trend: string; tone: string }) {
  return <div className="kpi-card"><div className={`kpi-icon ${tone}`}><Icon size={18} /></div><div className="kpi-copy"><span>{label}</span><strong>{value}</strong><small className={trend.startsWith('+') ? 'up' : 'down'}>{trend} <span>vs last 24h</span></small></div><ArrowUpRight className="kpi-arrow" size={16} /></div>
}
function SectionHeader({ title, subtitle, action }: { title: string; subtitle?: string; action?: string }) {
  return <div className="section-header"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{action && <button className="ghost-btn">{action} <ArrowUpRight size={14} /></button>}</div>
}

export default function ReliefDashboard() {
  const [section, setSection] = useState<Section>('Dashboard')
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [dark, setDark] = useState(false)
  const [search, setSearch] = useState('')
  const [notice, setNotice] = useState('')
  const [approved, setApproved] = useState<string[]>([])
  const [filter, setFilter] = useState('All statuses')
  const [showNotifications, setShowNotifications] = useState(false)
  const [showProfile, setShowProfile] = useState(false)
  const filteredRequests = useMemo(() => requests.filter(r => (filter === 'All statuses' || r.status === filter) && (!search || `${r.id} ${r.location} ${r.need}`.toLowerCase().includes(search.toLowerCase()))), [filter, search])
  function act(message: string) { setNotice(message); window.setTimeout(() => setNotice(''), 3000) }

  return <div className={`app-shell ${dark ? 'theme-dark' : ''}`}>
    <aside className={`sidebar ${sidebarOpen ? 'open' : ''}`}>
      <div className="brand"><div className="brand-mark"><ShieldCheck size={20} /></div><div><strong>Relief<span>Ops</span></strong><small>COMMAND CENTER</small></div><button className="sidebar-close" onClick={() => setSidebarOpen(false)}><X size={18} /></button></div>
      <div className="system-status"><span className="pulse-dot" /> <span>System operational</span><span className="status-live">LIVE</span></div>
      <nav><div className="nav-label">OPERATIONS</div>{nav.slice(0, 7).map(({ label, icon: Icon }) => <button key={label} className={section === label ? 'active' : ''} onClick={() => { setSection(label as Section); setSidebarOpen(false) }}><Icon size={17} /><span>{label}</span>{label === 'Relief Requests' && <b className="nav-count">18</b>}</button>)}<div className="nav-label secondary-label">GOVERNANCE</div>{nav.slice(7).map(({ label, icon: Icon }) => <button key={label} className={section === label ? 'active' : ''} onClick={() => { setSection(label as Section); setSidebarOpen(false) }}><Icon size={17} /><span>{label}</span></button>)}</nav>
      <div className="sidebar-footer"><div className="project-tag"><span className="project-dot" /><div><strong>Group 13</strong><small>Database Engineering</small></div></div><small className="version">v2.4.0 · KLU Hyderabad</small></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><button className="mobile-menu" onClick={() => setSidebarOpen(true)}><Menu size={21} /></button><div className="crumb"><span>Operations</span><b>/</b><strong>{section}</strong></div><div className="top-actions"><div className="search-wrap"><Search size={16} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search records..." aria-label="Search records" /><kbd>⌘ K</kbd></div><button className="icon-btn" onClick={() => setDark(!dark)} aria-label="Toggle theme">{dark ? <Sun size={18} /> : <Moon size={18} />}</button><div className="relative"><button className="icon-btn notification-btn" onClick={() => setShowNotifications(!showNotifications)} aria-label="Notifications"><Bell size={18} /><i /></button>{showNotifications && <div className="popover notifications"><strong>Notifications</strong><div><AlertTriangle size={15} color="#e36b35" /><span>REQ-1024 requires approval<small>2 minutes ago</small></span></div><div><Package size={15} color="#d39a2c" /><span>Water stock below threshold<small>18 minutes ago</small></span></div><div><Check size={15} color="#228b67" /><span>DEL-5008 confirmed<small>42 minutes ago</small></span></div></div>}</div><div className="relative"><button className="profile-chip" onClick={() => setShowProfile(!showProfile)}><span className="avatar">MR</span><span className="profile-text"><strong>Mohammad Reyhan</strong><small>Administrator</small></span><ChevronDown size={15} /></button>{showProfile && <div className="popover profile-pop"><strong>Account</strong><button onClick={() => act('Profile settings opened')}>Profile settings</button><button onClick={() => act('Signed out of demo session')}>Sign out</button></div>}</div></div></header>
      <div className="page-wrap">
        {section === 'Dashboard' ? <DashboardView onNavigate={setSection} onAction={act} /> : <ModuleView section={section} requests={filteredRequests} filter={filter} setFilter={setFilter} approved={approved} setApproved={setApproved} onAction={act} search={search} />}
      </div>
      {notice && <div className="toast"><Check size={16} /> {notice}</div>}
    </main>
  </div>
}

function DashboardView({ onNavigate, onAction }: { onNavigate: (s: Section) => void; onAction: (s: string) => void }) {
  return <>
    <div className="page-heading"><div><div className="eyebrow"><span className="pulse-dot" /> Tuesday, 21 September 2026 · 09:24 AM IST</div><h1>Emergency Operations Dashboard</h1><p>Coordinating verified needs across Hyderabad and surrounding response zones.</p></div><div className="heading-actions"><button className="outline-btn" onClick={() => onAction('Report generation started')}><FileText size={16} /> Generate report</button><button className="primary-btn" onClick={() => onNavigate('Incidents')}><Radio size={16} /> New incident</button></div></div>
    <div className="kpi-grid"><KPI icon={Radio} label="Active incidents" value="08" trend="+2.4%" tone="red" /><KPI icon={Users} label="Registered victims" value="12,486" trend="+8.1%" tone="blue" /><KPI icon={ClipboardCheck} label="Relief requests" value="327" trend="+12.6%" tone="amber" /><KPI icon={Package} label="Available resources" value="18,420" trend="-3.2%" tone="green" /><KPI icon={HeartHandshake} label="Active shelters" value="24" trend="+1.0%" tone="purple" /><KPI icon={Users} label="Volunteers deployed" value="186" trend="+5.8%" tone="cyan" /><KPI icon={Clock3} label="Pending approvals" value="18" trend="+4.3%" tone="orange" /><KPI icon={Truck} label="Deliveries in transit" value="42" trend="+9.2%" tone="indigo" /></div>
    <div className="dashboard-grid"><section className="panel incidents-panel"><SectionHeader title="Active incidents" subtitle="Live operational overview" action="View all incidents" /><div className="table-scroll"><table><thead><tr><th>Incident</th><th>Location</th><th>Severity</th><th>Affected</th><th>Status</th><th>Assigned team</th><th /></tr></thead><tbody>{incidents.map(i => <tr key={i.id}><td><strong>{i.id}</strong><small>{i.type} · {i.time}</small></td><td><span className="location"><MapPin size={13} />{i.location}</span></td><td><StatusBadge tone={severityTone(i.severity)}>{i.severity}</StatusBadge></td><td><strong>{i.people}</strong><small>people</small></td><td><StatusBadge tone={i.status === 'Active' ? 'critical' : 'warning'}><span className="status-dot" />{i.status}</StatusBadge></td><td>{i.team}</td><td><button className="row-menu" onClick={() => onAction(`Opened ${i.id}`)}>•••</button></td></tr>)}</tbody></table></div><div className="table-foot"><span>Showing 3 of 8 active incidents</span><button onClick={() => onNavigate('Incidents')}>Manage incidents <ArrowUpRight size={13} /></button></div></section>
      <section className="panel alerts-panel"><SectionHeader title="Requires attention" subtitle="Priority actions for your role" /><div className="attention-list"><div className="attention-item critical-item"><div className="attention-icon"><AlertTriangle size={16} /></div><div><strong>High-severity request</strong><p>REQ-1024 · Water allocation needs approval</p><small>2 minutes ago</small></div><button onClick={() => onNavigate('Relief Requests')}>Review</button></div><div className="attention-item warning-item"><div className="attention-icon"><Package size={16} /></div><div><strong>Stock threshold reached</strong><p>Essential Medicines · 28% remaining</p><small>18 minutes ago</small></div><button onClick={() => onNavigate('Inventory')}>Inspect</button></div><div className="attention-item info-item"><div className="attention-icon"><Truck size={16} /></div><div><strong>Delivery in transit</strong><p>DEL-5012 · ETA 10:25 AM</p><small>34 minutes ago</small></div><button onClick={() => onNavigate('Deliveries')}>Track</button></div></div><div className="attention-footer"><LockKeyhole size={14} /> All critical actions require authorized approval</div></section></div>
    <div className="dashboard-grid lower-grid"><section className="panel allocation-panel"><SectionHeader title="Priority allocation queue" subtitle="Human approval required before dispatch" action="Open allocation" /><div className="allocation-summary"><div className="score-ring"><strong>96</strong><span>top score</span></div><div><span className="eyebrow">REQ-1024 · HYDERABAD</span><h3>Drinking water allocation</h3><p>1,200 L requested · 850 people affected · Immediate urgency</p><div className="allocation-meta"><StatusBadge tone="critical">Critical</StatusBadge><StatusBadge tone="warning">Pending approval</StatusBadge><span><Clock3 size={13} /> SLA 22 min</span></div></div></div><div className="recommendation"><div><Zap size={15} /><strong>Recommended allocation</strong></div><span>1,000 L <small>of 1,200 L requested</small></span><button className="approve-btn" onClick={() => onAction('Allocation recommendation opened')}>Review recommendation</button></div></section><section className="panel workflow-panel"><SectionHeader title="Response workflow" subtitle="REQ-1024 current state" /><div className="workflow-steps">{['Need verified', 'Stock reserved', 'Approval', 'Dispatch', 'Delivered'].map((s, i) => <div className={`workflow-step ${i < 2 ? 'done' : i === 2 ? 'current' : ''}`} key={s}><div className="step-icon">{i < 2 ? <Check size={14} /> : i === 2 ? <Clock3 size={14} /> : <span>{i + 1}</span>}</div><span>{s}</span></div>)}</div><div className="workflow-note"><ShieldCheck size={16} /><span>Allocation is paused until an authorized coordinator approves.</span></div></section></div>
  </>
}

function ModuleView({ section, requests, filter, setFilter, approved, setApproved, onAction, search }: { section: Section; requests: typeof requests; filter: string; setFilter: (s: string) => void; approved: string[]; setApproved: (s: string[]) => void; onAction: (s: string) => void; search: string }) {
  const titles: Record<string, [string, string]> = { Incidents: ['Incident management', 'Track, verify and coordinate active disaster response.'], 'Relief Requests': ['Relief requests & priority allocation', 'Prioritize verified needs while keeping every critical decision human-controlled.'], Inventory: ['Inventory management', 'Trace stock movement from warehouse batch to field delivery.'], Shelters: ['Shelter management', 'Monitor capacity and coordinate safe accommodation.'], Volunteers: ['Volunteer management', 'Deploy verified people and skills where they are needed most.'], Deliveries: ['Relief distribution & delivery tracking', 'Follow each allocation from dispatch to confirmed receipt.'], 'Audit Trail': ['Audit & traceability', 'Immutable operational history across the relief chain.'], 'Reports & Analytics': ['Reports & analytics', 'Scenario-based operational intelligence for review and planning.'], 'Users & Permissions': ['Users & permissions', 'Role-based control for sensitive relief operations.'], 'Decision Support': ['Decision support — future AI layer', 'Prototype concepts for responsible decision support.'] }
  const [title, subtitle] = titles[section]
  return <><div className="page-heading"><div><div className="eyebrow">OPERATIONS / {section.toUpperCase()}</div><h1>{title}</h1><p>{subtitle}</p></div><div className="heading-actions"><button className="outline-btn" onClick={() => onAction('Export queued for download')}><FileText size={16} /> Export</button><button className="primary-btn" onClick={() => onAction(`${section} form opened`)}><span>+</span> {section === 'Incidents' ? 'New incident' : 'Create record'}</button></div></div>{section === 'Relief Requests' ? <RequestsModule requests={requests} filter={filter} setFilter={setFilter} approved={approved} setApproved={setApproved} onAction={onAction} /> : section === 'Inventory' ? <InventoryModule onAction={onAction} /> : section === 'Deliveries' ? <DeliveriesModule onAction={onAction} /> : section === 'Audit Trail' ? <AuditModule /> : section === 'Decision Support' ? <DecisionModule onAction={onAction} /> : <GenericModule section={section} onAction={onAction} search={search} />}</>
}

function RequestsModule({ requests: data, filter, setFilter, approved, setApproved, onAction }: { requests: typeof requests; filter: string; setFilter: (s: string) => void; approved: string[]; setApproved: (s: string[]) => void; onAction: (s: string) => void }) { return <><div className="info-banner"><div className="info-symbol"><Gauge size={19} /></div><div><strong>Controlled priority allocation</strong><p>Priority scores support coordinators by considering severity, affected population, urgency, access conditions and destination capacity. Recommendations never commit resources automatically.</p></div><StatusBadge tone="info">Human approval required</StatusBadge></div><div className="module-stats"><div><span>Open requests</span><strong>327</strong><small>+12.6% today</small></div><div><span>Immediate urgency</span><strong>42</strong><small className="warn">Requires action</small></div><div><span>Approved today</span><strong>86</strong><small className="success-text">74% fulfilment rate</small></div><div><span>Avg. response time</span><strong>18m</strong><small>Within 30m SLA</small></div></div><section className="panel module-panel"><div className="toolbar"><div className="filter-tabs">{['All statuses', 'Pending Approval', 'Approved'].map(v => <button key={v} className={filter === v ? 'selected' : ''} onClick={() => setFilter(v)}>{v}</button>)}</div><button className="outline-btn small" onClick={() => onAction('Priority recommendation generated')}><Zap size={14} /> Generate recommendation</button></div><div className="table-scroll"><table><thead><tr><th>Request</th><th>Need / quantity</th><th>Severity</th><th>Affected</th><th>Priority</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.map(r => <tr key={r.id}><td><strong>{r.id}</strong><small><MapPin size={11} /> {r.location}</small></td><td><strong>{r.need}</strong><small>{r.qty} requested</small></td><td><StatusBadge tone={severityTone(r.severity)}>{r.severity}</StatusBadge><small>{r.urgency}</small></td><td>{r.affected}</td><td><div className="priority"><strong>{r.score}</strong><div><span style={{ width: `${r.score}%` }} /></div></div></td><td><StatusBadge tone={approved.includes(r.id) || r.status === 'Approved' ? 'success' : 'warning'}>{approved.includes(r.id) ? 'Approved' : r.status}</StatusBadge></td><td>{approved.includes(r.id) ? <button className="row-action done" onClick={() => onAction(`${r.id} is approved`)}><Check size={14} /> Approved</button> : <button className="row-action" onClick={() => { setApproved([...approved, r.id]); onAction(`${r.id} approved — audit entry created`) }}>Approve</button>}</td></tr>)}</tbody></table></div></section></> }
function InventoryModule({ onAction }: { onAction: (s: string) => void }) { return <><div className="module-stats"><div><span>Total inventory</span><strong>26,840</strong><small>Across 6 categories</small></div><div><span>Available</span><strong>18,420</strong><small className="success-text">68.6% available</small></div><div><span>Allocated</span><strong>5,980</strong><small>22.3% reserved</small></div><div><span>Low stock alerts</span><strong className="orange-number">05</strong><small className="warn">Requires replenishment</small></div></div><section className="panel module-panel"><SectionHeader title="Resource inventory" subtitle="Batch-level stock traceability" action="View movement history" /><div className="table-scroll"><table><thead><tr><th>Resource</th><th>Category / warehouse</th><th>Batch</th><th>Available</th><th>Allocated</th><th>Stock level</th><th>Status</th></tr></thead><tbody>{inventory.map(r => <tr key={r.id}><td><strong>{r.name}</strong><small>{r.id}</small></td><td>{r.cat}<small>{r.warehouse}</small></td><td>{r.batch}<small>Expiry {r.expiry}</small></td><td><strong>{r.available}</strong></td><td>{r.allocated}</td><td><div className="stock-cell"><div className="stock-bar"><span className={r.stock < 35 ? 'low' : ''} style={{ width: `${r.stock}%` }} /></div><small>{r.stock}%</small></div></td><td><StatusBadge tone={r.stock < 35 ? 'warning' : 'success'}>{r.status}</StatusBadge></td></tr>)}</tbody></table></div><div className="low-stock"><AlertTriangle size={15} /><strong>5 resources require replenishment.</strong><button onClick={() => onAction('Replenishment report opened')}>Review alerts</button></div></section></> }
function DeliveriesModule({ onAction }: { onAction: (s: string) => void }) { return <><div className="delivery-flow">{['Verified need', 'Stock reserved', 'Approval', 'Dispatched', 'In transit', 'Delivered', 'Confirmed'].map((s, i) => <div key={s} className={i < 4 ? 'flow-done' : i === 4 ? 'flow-current' : ''}><span>{i < 4 ? <Check size={14} /> : i + 1}</span><small>{s}</small>{i < 6 && <b />}</div>)}</div><section className="panel module-panel"><SectionHeader title="Delivery tracking" subtitle="End-to-end chain of custody" action="View all deliveries" /><div className="table-scroll"><table><thead><tr><th>Delivery</th><th>Resource</th><th>Destination</th><th>Driver / team</th><th>Dispatch / ETA</th><th>Status</th><th /></tr></thead><tbody>{deliveries.map(d => <tr key={d.id}><td><strong>{d.id}</strong><small>{d.request}</small></td><td><strong>{d.resource}</strong><small>{d.qty}</small></td><td><span className="location"><MapPin size={13} />{d.destination}</span><small>from {d.origin}</small></td><td>{d.driver}</td><td>{d.time}<small>ETA {d.eta}</small></td><td><StatusBadge tone={d.status === 'Confirmed' ? 'success' : d.status === 'In Transit' ? 'info' : 'warning'}><span className="status-dot" />{d.status}</StatusBadge></td><td><button className="row-action" onClick={() => onAction(d.status === 'In Transit' ? `${d.id} tracking opened` : `Confirmation details opened for ${d.id}`)}>{d.status === 'In Transit' ? 'Track' : 'View'}</button></td></tr>)}</tbody></table></div></section></> }
function AuditModule() { const logs = [['09:10:22','Coordinator','Dispatch created','DEL-5012','Approved'],['08:51:04','Inventory Manager','Stock reserved','Water · Batch B12','Recorded'],['08:45:11','Administrator','Allocation approved','REQ-1024','Authorized'],['08:32:48','Field Responder','Incident reported','INC-2026-001','Verified'],['08:18:36','Shelter Coordinator','Occupancy updated','SHEL-008','Recorded']]; return <section className="panel module-panel"><div className="audit-head"><div><h2>Immutable activity log</h2><p>Every change is attributable, timestamped and traceable across the response chain.</p></div><div className="audit-chain"><span>Incident</span><b>→</b><span>Need</span><b>→</b><span>Allocation</span><b>→</b><span>Delivery</span></div></div><div className="audit-table">{logs.map(l => <div className="audit-row" key={l[0]}><LockKeyhole size={15} /><span className="audit-time">{l[0]}</span><strong>{l[1]}</strong><span>{l[2]}</span><code>{l[3]}</code><StatusBadge tone={l[4] === 'Authorized' ? 'success' : 'neutral'}>{l[4]}</StatusBadge></div>)}</div></section> }
function DecisionModule({ onAction }: { onAction: (s: string) => void }) { return <><div className="future-banner"><div className="future-icon"><Zap size={22} /></div><div><StatusBadge tone="info">Future enhancement / decision support prototype</StatusBadge><h2>AI-informed, human-controlled response</h2><p>Explore how a future decision-support layer could help teams forecast demand and optimize resources without ever committing relief automatically.</p></div></div><div className="ai-grid">{[['Demand prediction','Forecast resource needs by incident type and household profile.',CloudRain],['Resource optimization','Suggest balanced allocations across available inventory.',Boxes],['Route optimization','Surface safer dispatch routes based on access conditions.',MapPin],['Shortage prediction','Identify likely stock-outs before they affect delivery.',AlertTriangle]].map(([t,d,I]) => <div className="ai-card" key={t as string}><div><I size={18} /></div><h3>{t as string}</h3><p>{d as string}</p><span>Prototype concept <ArrowUpRight size={13} /></span></div>)}</div><section className="panel approval-rail"><div className="rail-title"><ShieldCheck size={18} /><div><h3>Decision control rail</h3><p>AI recommendation → Human review → Approval → Allocation</p></div></div><button className="primary-btn" onClick={() => onAction('Decision support preview opened')}>Explore prototype</button></section></> }
function GenericModule({ section, onAction, search }: { section: Section; onAction: (s: string) => void; search: string }) { const rows = section === 'Incidents' ? incidents.map(i => [i.id, i.type, i.location, i.severity, i.people, i.status]) : section === 'Shelters' ? [['SHEL-008','Community Hall A','Hyderabad','500','420','Near Capacity'],['SHEL-014','Govt. School B','Warangal','320','198','Available'],['SHEL-021','Relief Camp C','Nalgonda','180','180','Full']] : section === 'Volunteers' ? [['VOL-1842','Aarav Reddy','Medical','Hyderabad','On mission','INC-001'],['VOL-1920','Sana Khan','Logistics','Warangal','Available','—'],['VOL-2077','Vikram Rao','Rescue','Nalgonda','Deployed','INC-003']] : [['RPT-2026-09','Daily relief report','Operations','Generated today'],['RPT-2026-08','Shelter capacity report','Shelters','Updated 09:00'],['RPT-2026-07','Volunteer deployment','People','Updated 08:45']]; return <><div className="module-stats"><div><span>Total records</span><strong>{section === 'Incidents' ? '08' : section === 'Shelters' ? '24' : section === 'Volunteers' ? '1,284' : '06'}</strong><small>Centralized records</small></div><div><span>Verified</span><strong>92%</strong><small className="success-text">Audit compliant</small></div><div><span>Active today</span><strong>186</strong><small>Across response zones</small></div><div><span>Needs attention</span><strong className="orange-number">12</strong><small className="warn">Review queue</small></div></div><section className="panel module-panel"><div className="toolbar"><div className="table-title"><h2>{section} register</h2><p>Relational records · last synced just now</p></div><button className="outline-btn small" onClick={() => onAction('Filters opened')}><ListFilter size={14} /> Filters</button></div><div className="table-scroll"><table><thead><tr>{(section === 'Incidents' ? ['ID','Type','Location','Severity','Affected','Status'] : section === 'Shelters' ? ['Shelter ID','Name','Location','Capacity','Occupied','Status'] : section === 'Volunteers' ? ['Volunteer ID','Name','Skill','Location','Availability','Incident'] : ['Report ID','Name','Domain','Status']).map(h => <th key={h}>{h}</th>)}<th>Action</th></tr></thead><tbody>{rows.filter(row => !search || row.join(' ').toLowerCase().includes(search.toLowerCase())).map(row => <tr key={row[0]}>{row.map((v, i) => <td key={v}><strong>{i === 0 ? v : ''}</strong>{i !== 0 && (v === 'Critical' || v === 'High' || v === 'Active' || v === 'Near Capacity' || v === 'Full' || v === 'On mission' ? <StatusBadge tone={severityTone(v)}>{v}</StatusBadge> : v)}{i === 0 && <small>{section === 'Incidents' ? 'Operational record' : 'Database entity'}</small>}</td>)}<td><button className="row-action" onClick={() => onAction(`Opened ${row[0]}`)}>View</button></td></tr>)}</tbody></table></div></section></> }

// Supporting CSS lives in app/globals.css to keep the module portable.

function Unused() { return null }

export { Unused }
